// react/src/components/PqrsCard.tsx
const PqrsCard = () => <div className="card">
  <div className="card-header d-flex justify-content-center"><h6>Created by: </h6><h6>Status: </h6></div>
  <div className="card-body">
    <h5 className="card-title">Placeholder</h5>
    <p className="card-text">Placeholder</p>
  </div>
  <div className="card-footer">Created on:</div>
</div>

export default PqrsCard;

// vue/src/components/PqrsCard.vue
<template>
  <div class="card">
    <div class="card-header d-flex justify-content-between">
      <h6>
        Created by:
        <slot name="creator"></slot>
      </h6>
      <h6>
        Status:
        <slot name="status"></slot>
      </h6>
    </div>
    <div class="card-body">
      <h5 class="card-title">
        <slot></slot>
      </h5>
      <p class="card-text">
        <slot name="description"></slot>
      </p>
    </div>
    <div class="card-footer">
      Created on
      <slot name="creation-date"></slot>
    </div>
  </div>
</template>
