// vue/src/views/LoginView.vue
<template>
  <main class="d-flex justify-content-center align-items-center">
    <TheLoginForm
      v-model:email="email"
      v-model:password="password"
      @submit="handleSubmit"
    />
  </main>
</template>

<script lang="ts" setup>
import TheLoginForm from "@/components/TheLoginForm.vue";
import { ref } from "vue";
import { useAuthStore } from "@/stores/authStore";
import { useRouter } from "vue-router";
import { authenticateUser } from "@/services/auth";

const email = ref("");
const password = ref("");

const auth = useAuthStore();
const router = useRouter();

const handleSubmit = async () => {
  try {
    const { accessToken, refreshToken } = await authenticateUser(
      email.value,
      password.value
    );

    auth.setAccessToken(accessToken);
    auth.setRefreshToken(refreshToken);

    await router.replace({ name: "home" });
  } catch (e) {
    console.error(e);
  }
};
</script>

<style scoped>
main {
  height: 100vh;
}
</style>

// react/src/views/LoginView.tsx
import TheLoginForm from "@/components/TheLoginForm";
import {authenticateUser} from "@/services/auth";
import {useNavigate} from "react-router-dom";
import {FormEvent} from "react";
import tokenService from "@/services/tokenService";

const LoginView = () => {
  const navigate = useNavigate();

  const handleSubmit = async (e: FormEvent, email: string, password: string) => {
    e.preventDefault();

    const {accessToken, refreshToken} = await authenticateUser(email, password);

    tokenService.accessToken = accessToken;
    tokenService.refreshToken = refreshToken;

    navigate("/", {replace: true});
  }

  return <main className="d-flex justify-content-center align-items-center vh-100">
    <TheLoginForm onSubmit={handleSubmit}/>
  </main>;
}

export default LoginView;
